### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by Lewiscowles1986** [ViGrey/neszip-example#1]
It'd be nice to see a screenshot of the file open in a zip editor with an emulator window showing the game.

**Comment by ViGrey** [comment]
I wrote a blog post about this project at https://vigrey.com/blog/this-nes-rom-also-zip-file that includes a screenshot.  To minimize the zip file size and complexity, I'm not going to include a screenshot in this source code.  I'm also not going to include a link to the blog post just in case I end up changing how my blog post URLs are formatted in the future.  My apologies for not including these.
